### ISSUE TITLE
dynamic - static builds

### ISSUE THREAD

**Issue by NN---** [ksmyth/protobuf#1]
Please add 'static' build.
Current build is only 'dynamic'.

It is easy to do it by simple change:

```
[x64,v100,release] { 
            lib += vsprojects\x64\Release\libprotobuf.lib;
            vcpdb += vsprojects\x64\Release\vc100.pdb;
        }
```

To

```
[x64,v100,release,dynamic] { 
            lib += vsprojects\x64\Release\Dynamic\libprotobuf.lib;
            vcpdb += vsprojects\x64\Release\Dynamic\vc100.pdb;
        }

[x64,v100,release,static] { 
            lib += vsprojects\x64\Release\Static\libprotobuf.lib;
            vcpdb += vsprojects\x64\Release\Static\vc100.pdb;
        }
```

Additional build configuration is needed of course.

**Comment by ksmyth** [comment]
It is static only right now, no?

vsprojects/readme.txt contains "Due to issues with Win32's use of a separate heap for each DLL, as well as binary compatibility issues between different versions of MSVC's STL library, it is
recommended that you use static linkage only."

Also because of the increased test burden and file sizes, I don't want to make .dlls.

**Comment by ksmyth** [comment]
Maybe I mistook what you mean. Do you mean add a static .lib that links against static C runtime? Using the static C runtime is somewhat rare, and I don't want to support it

**Comment by NN---** [comment]
It's a little bit confusing.
I mean /MD (multithreaded dll) and /MT (multithreaded).
Both create a regular lib file not dll.

**Comment by NN---** [comment]
I don't have statistics to say whether it is rare or not but it is used.
